% =========================================================
% GENERATED PLANT GROWTH FACTS
% =========================================================
% Generated by scripts/generate_growth_facts.py
% Do not edit manually.
%
% Sources:
% - Iowa State University Extension: https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables
% - Wisconsin Horticulture Extension: https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/
% - RHS HTML Germination Guide: https://www.rhs.org.uk/membership/rhs-members-seed-scheme/germination-guide
% - RHS PDF Germination Guide: https://www.rhs.org.uk/membership/pdfs/seed-scheme/harvested-seed-germination-requirements.pdf
%
% Notes:
% - Iowa/Wisconsin facts are crop/common-name level.
% - RHS facts are merged by genus using plant_taxonomy_fact.pl.
% - RHS should be treated as genus-level enrichment.
% =========================================================

% =========================================================
% GROWTH FACTS BY PLANT
% Auto-organized by plant_data_bank_scripts/scripts/reorder_prolog_facts_by_plant.py
% =========================================================

% ---------------------------------------------------------
% ANNUAL ASTER
% ---------------------------------------------------------

% =========================================================
% GROWTH FACTS BY PLANT
% Auto-organized by plant_data_bank_scripts/scripts/reorder_prolog_facts_by_plant.py
% =========================================================

% ---------------------------------------------------------
% ANNUAL ASTER
% ---------------------------------------------------------
fact_scope(annual_aster, common_crop).
germination_days_min(annual_aster, 7).
germination_days_max(annual_aster, 10).
germination_light(annual_aster, lightly_cover).
stratification_required(annual_aster, false).
stratification_days_min(annual_aster, 0).
stratification_days_max(annual_aster, 0).
sowing_depth_cm(annual_aster, 0.3).
special_treatment(annual_aster, keep_close_to_surface).
special_treatment(annual_aster, lightly_cover_seed).
source_name(annual_aster, 'Iowa State University Extension').
source_url(annual_aster, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(annual_aster, high).

% ---------------------------------------------------------
% ANNUAL STATICE
% ---------------------------------------------------------
fact_scope(annual_statice, common_crop).
germination_days_min(annual_statice, 7).
germination_days_max(annual_statice, 10).
germination_light(annual_statice, lightly_cover).
stratification_required(annual_statice, false).
stratification_days_min(annual_statice, 0).
stratification_days_max(annual_statice, 0).
sowing_depth_cm(annual_statice, 0.3).
special_treatment(annual_statice, keep_close_to_surface).
special_treatment(annual_statice, lightly_cover_seed).
source_name(annual_statice, 'Iowa State University Extension').
source_url(annual_statice, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(annual_statice, high).

% ---------------------------------------------------------
% ASPARAGUS
% ---------------------------------------------------------
fact_scope(asparagus, common_crop).
stratification_required(asparagus, false).
stratification_days_min(asparagus, 0).
stratification_days_max(asparagus, 0).
minimum_soil_temp_c(asparagus, 10.0).
optimum_soil_temp_c(asparagus, 23.9).
viable_temp_min_c(asparagus, 15.6).
viable_temp_max_c(asparagus, 29.4).
source_name(asparagus, 'Wisconsin Horticulture Extension').
source_url(asparagus, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(asparagus, medium).

% ---------------------------------------------------------
% BACHELOR
% ---------------------------------------------------------
fact_scope(bachelor, common_crop).
germination_days_min(bachelor, 7).
germination_days_max(bachelor, 14).
germination_light(bachelor, lightly_cover).
stratification_required(bachelor, false).
stratification_days_min(bachelor, 0).
stratification_days_max(bachelor, 0).
sowing_depth_cm(bachelor, 0.3).
special_treatment(bachelor, keep_close_to_surface).
special_treatment(bachelor, lightly_cover_seed).
source_name(bachelor, 'Iowa State University Extension').
source_url(bachelor, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(bachelor, high).

% ---------------------------------------------------------
% BASIL
% ---------------------------------------------------------
fact_scope(basil, common_crop).
accepted_scientific_name(basil, 'Ocimum basilicum').
genus(basil, ocimum).
family(basil, lamiaceae).
germination_days_min(basil, 10).
germination_days_max(basil, 14).
germination_light(basil, darkness_required).
stratification_required(basil, false).
stratification_days_min(basil, 0).
stratification_days_max(basil, 0).
sowing_depth_cm(basil, 0.95).
special_treatment(basil, cover_seed).
special_treatment(basil, inferred_depth_from_1_4_to_1_2_inch).
source_name(basil, 'Iowa State University Extension').
source_url(basil, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(basil, high).

% ---------------------------------------------------------
% BEAN
% ---------------------------------------------------------
fact_scope(bean, common_crop).
stratification_required(bean, false).
stratification_days_min(bean, 0).
stratification_days_max(bean, 0).
minimum_soil_temp_c(bean, 22.2).
optimum_soil_temp_c(bean, 26.7).
viable_temp_min_c(bean, 15.6).
viable_temp_max_c(bean, 35.0).
source_name(bean, 'Wisconsin Horticulture Extension').
source_url(bean, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(bean, medium).

% ---------------------------------------------------------
% BEAN BUSH
% ---------------------------------------------------------
fact_scope(bean_bush, common_crop).
accepted_scientific_name(bean_bush, 'Phaseolus vulgaris').
genus(bean_bush, phaseolus).
family(bean_bush, fabaceae).
stratification_required(bean_bush, false).
stratification_days_min(bean_bush, 0).
stratification_days_max(bean_bush, 0).
minimum_soil_temp_c(bean_bush, 22.2).
optimum_soil_temp_c(bean_bush, 26.7).
viable_temp_min_c(bean_bush, 15.6).
viable_temp_max_c(bean_bush, 35.0).
source_name(bean_bush, 'Wisconsin Horticulture Extension').
source_url(bean_bush, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(bean_bush, medium).

% ---------------------------------------------------------
% BEAN POLE
% ---------------------------------------------------------
fact_scope(bean_pole, common_crop).
accepted_scientific_name(bean_pole, 'Phaseolus vulgaris').
genus(bean_pole, phaseolus).
family(bean_pole, fabaceae).
stratification_required(bean_pole, false).
stratification_days_min(bean_pole, 0).
stratification_days_max(bean_pole, 0).
minimum_soil_temp_c(bean_pole, 22.2).
optimum_soil_temp_c(bean_pole, 26.7).
viable_temp_min_c(bean_pole, 15.6).
viable_temp_max_c(bean_pole, 35.0).
source_name(bean_pole, 'Wisconsin Horticulture Extension').
source_url(bean_pole, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(bean_pole, medium).

% ---------------------------------------------------------
% BEANS
% ---------------------------------------------------------
fact_scope(beans, common_crop).
stratification_required(beans, false).
stratification_days_min(beans, 0).
stratification_days_max(beans, 0).
minimum_soil_temp_c(beans, 22.2).
optimum_soil_temp_c(beans, 26.7).
viable_temp_min_c(beans, 15.6).
viable_temp_max_c(beans, 35.0).
source_name(beans, 'Wisconsin Horticulture Extension').
source_url(beans, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(beans, medium).

% ---------------------------------------------------------
% BEANS BUSH
% ---------------------------------------------------------
fact_scope(beans_bush, common_crop).
stratification_required(beans_bush, false).
stratification_days_min(beans_bush, 0).
stratification_days_max(beans_bush, 0).
minimum_soil_temp_c(beans_bush, 22.2).
optimum_soil_temp_c(beans_bush, 26.7).
viable_temp_min_c(beans_bush, 15.6).
viable_temp_max_c(beans_bush, 35.0).
source_name(beans_bush, 'Wisconsin Horticulture Extension').
source_url(beans_bush, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(beans_bush, medium).

% ---------------------------------------------------------
% BEANS POLE
% ---------------------------------------------------------
fact_scope(beans_pole, common_crop).
stratification_required(beans_pole, false).
stratification_days_min(beans_pole, 0).
stratification_days_max(beans_pole, 0).
minimum_soil_temp_c(beans_pole, 22.2).
optimum_soil_temp_c(beans_pole, 26.7).
viable_temp_min_c(beans_pole, 15.6).
viable_temp_max_c(beans_pole, 35.0).
source_name(beans_pole, 'Wisconsin Horticulture Extension').
source_url(beans_pole, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(beans_pole, medium).

% ---------------------------------------------------------
% BEET
% ---------------------------------------------------------
fact_scope(beet, common_crop).
accepted_scientific_name(beet, 'Beta vulgaris').
genus(beet, beta).
family(beet, amaranthaceae).
germination_days_min(beet, 5).
germination_days_max(beet, 8).
germination_light(beet, darkness_required).
stratification_required(beet, false).
stratification_days_min(beet, 0).
stratification_days_max(beet, 0).
sowing_depth_cm(beet, 0.95).
special_treatment(beet, cover_seed).
special_treatment(beet, inferred_depth_from_1_4_to_1_2_inch).
source_name(beet, 'Iowa State University Extension').
source_url(beet, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(beet, high).

% ---------------------------------------------------------
% BELL PEPPER
% ---------------------------------------------------------
fact_scope(bell_pepper, common_crop).
accepted_scientific_name(bell_pepper, 'Capsicum annuum').
genus(bell_pepper, capsicum).
family(bell_pepper, solanaceae).
germination_days_min(bell_pepper, 7).
germination_days_max(bell_pepper, 10).
germination_light(bell_pepper, darkness_required).
stratification_required(bell_pepper, false).
stratification_days_min(bell_pepper, 0).
stratification_days_max(bell_pepper, 0).
sowing_depth_cm(bell_pepper, 0.95).
minimum_soil_temp_c(bell_pepper, 18.3).
optimum_soil_temp_c(bell_pepper, 29.4).
viable_temp_min_c(bell_pepper, 15.6).
viable_temp_max_c(bell_pepper, 35.0).
special_treatment(bell_pepper, cover_seed).
special_treatment(bell_pepper, inferred_depth_from_1_4_to_1_2_inch).
source_name(bell_pepper, 'Iowa State University Extension').
source_name(bell_pepper, 'Wisconsin Horticulture Extension').
source_url(bell_pepper, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(bell_pepper, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(bell_pepper, high).

% ---------------------------------------------------------
% BLACK EYED SUSAN
% ---------------------------------------------------------
fact_scope(black_eyed_susan, common_crop).
germination_days_min(black_eyed_susan, 7).
germination_days_max(black_eyed_susan, 14).
germination_light(black_eyed_susan, lightly_cover).
stratification_required(black_eyed_susan, false).
stratification_days_min(black_eyed_susan, 0).
stratification_days_max(black_eyed_susan, 0).
sowing_depth_cm(black_eyed_susan, 0.3).
special_treatment(black_eyed_susan, keep_close_to_surface).
special_treatment(black_eyed_susan, lightly_cover_seed).
source_name(black_eyed_susan, 'Iowa State University Extension').
source_url(black_eyed_susan, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(black_eyed_susan, high).

% ---------------------------------------------------------
% BROCCOLI
% ---------------------------------------------------------
fact_scope(broccoli, common_crop).
accepted_scientific_name(broccoli, 'Brassica oleracea var. italica').
genus(broccoli, brassica).
family(broccoli, brassicaceae).
germination_days_min(broccoli, 4).
germination_days_max(broccoli, 7).
germination_light(broccoli, darkness_required).
stratification_required(broccoli, false).
stratification_days_min(broccoli, 0).
stratification_days_max(broccoli, 0).
sowing_depth_cm(broccoli, 0.95).
special_treatment(broccoli, cover_seed).
special_treatment(broccoli, inferred_depth_from_1_4_to_1_2_inch).
source_name(broccoli, 'Iowa State University Extension').
source_url(broccoli, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(broccoli, high).

% ---------------------------------------------------------
% BRUSSELS SPROUTS
% ---------------------------------------------------------
fact_scope(brussels_sprouts, common_crop).
germination_days_min(brussels_sprouts, 5).
germination_days_max(brussels_sprouts, 8).
germination_light(brussels_sprouts, darkness_required).
stratification_required(brussels_sprouts, false).
stratification_days_min(brussels_sprouts, 0).
stratification_days_max(brussels_sprouts, 0).
sowing_depth_cm(brussels_sprouts, 0.95).
special_treatment(brussels_sprouts, cover_seed).
special_treatment(brussels_sprouts, inferred_depth_from_1_4_to_1_2_inch).
source_name(brussels_sprouts, 'Iowa State University Extension').
source_url(brussels_sprouts, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(brussels_sprouts, high).

% ---------------------------------------------------------
% CABBAGE
% ---------------------------------------------------------
fact_scope(cabbage, common_crop).
accepted_scientific_name(cabbage, 'Brassica oleracea var. capitata').
genus(cabbage, brassica).
family(cabbage, brassicaceae).
germination_days_min(cabbage, 4).
germination_days_max(cabbage, 7).
germination_light(cabbage, darkness_required).
stratification_required(cabbage, false).
stratification_days_min(cabbage, 0).
stratification_days_max(cabbage, 0).
sowing_depth_cm(cabbage, 0.95).
minimum_soil_temp_c(cabbage, 12.8).
optimum_soil_temp_c(cabbage, 29.4).
viable_temp_min_c(cabbage, 4.4).
viable_temp_max_c(cabbage, 40.6).
special_treatment(cabbage, cover_seed).
special_treatment(cabbage, inferred_depth_from_1_4_to_1_2_inch).
source_name(cabbage, 'Iowa State University Extension').
source_name(cabbage, 'Wisconsin Horticulture Extension').
source_url(cabbage, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(cabbage, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(cabbage, high).

% ---------------------------------------------------------
% CANTALOUPE
% ---------------------------------------------------------
fact_scope(cantaloupe, common_crop).
stratification_required(cantaloupe, false).
stratification_days_min(cantaloupe, 0).
stratification_days_max(cantaloupe, 0).
minimum_soil_temp_c(cantaloupe, 20.0).
optimum_soil_temp_c(cantaloupe, 32.2).
viable_temp_min_c(cantaloupe, 15.6).
viable_temp_max_c(cantaloupe, 37.8).
source_name(cantaloupe, 'Wisconsin Horticulture Extension').
source_url(cantaloupe, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(cantaloupe, medium).

% ---------------------------------------------------------
% CARROTS
% ---------------------------------------------------------
fact_scope(carrots, common_crop).
germination_days_min(carrots, 7).
germination_days_max(carrots, 21).
germination_light(carrots, darkness_required).
stratification_required(carrots, false).
stratification_days_min(carrots, 0).
stratification_days_max(carrots, 0).
sowing_depth_cm(carrots, 0.95).
minimum_soil_temp_c(carrots, 7.2).
optimum_soil_temp_c(carrots, 26.7).
viable_temp_min_c(carrots, 4.4).
viable_temp_max_c(carrots, 35.0).
special_treatment(carrots, cover_seed).
special_treatment(carrots, inferred_depth_from_1_4_to_1_2_inch).
source_name(carrots, 'Iowa State University Extension').
source_name(carrots, 'Wisconsin Horticulture Extension').
source_url(carrots, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(carrots, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(carrots, high).

% ---------------------------------------------------------
% CAULIFLOWER
% ---------------------------------------------------------
fact_scope(cauliflower, common_crop).
accepted_scientific_name(cauliflower, 'Brassica oleracea var. botrytis').
genus(cauliflower, brassica).
family(cauliflower, brassicaceae).
germination_days_min(cauliflower, 4).
germination_days_max(cauliflower, 7).
germination_light(cauliflower, darkness_required).
stratification_required(cauliflower, false).
stratification_days_min(cauliflower, 0).
stratification_days_max(cauliflower, 0).
sowing_depth_cm(cauliflower, 0.95).
minimum_soil_temp_c(cauliflower, 12.8).
optimum_soil_temp_c(cauliflower, 26.7).
viable_temp_min_c(cauliflower, 4.4).
viable_temp_max_c(cauliflower, 37.8).
special_treatment(cauliflower, cover_seed).
special_treatment(cauliflower, inferred_depth_from_1_4_to_1_2_inch).
source_name(cauliflower, 'Iowa State University Extension').
source_name(cauliflower, 'Wisconsin Horticulture Extension').
source_url(cauliflower, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(cauliflower, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(cauliflower, high).

% ---------------------------------------------------------
% CELERY
% ---------------------------------------------------------
fact_scope(celery, common_crop).
germination_days_min(celery, 14).
germination_days_max(celery, 21).
germination_light(celery, lightly_cover).
stratification_required(celery, false).
stratification_days_min(celery, 0).
stratification_days_max(celery, 0).
sowing_depth_cm(celery, 0.3).
minimum_soil_temp_c(celery, 18.3).
optimum_soil_temp_c(celery, 21.1).
viable_temp_min_c(celery, 4.4).
viable_temp_max_c(celery, 29.4).
special_treatment(celery, keep_close_to_surface).
special_treatment(celery, lightly_cover_seed).
source_name(celery, 'Iowa State University Extension').
source_name(celery, 'Wisconsin Horticulture Extension').
source_url(celery, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(celery, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(celery, high).

% ---------------------------------------------------------
% CHILI PEPPER
% ---------------------------------------------------------
fact_scope(chili_pepper, common_crop).
accepted_scientific_name(chili_pepper, 'Capsicum annuum').
genus(chili_pepper, capsicum).
family(chili_pepper, solanaceae).
germination_days_min(chili_pepper, 7).
germination_days_max(chili_pepper, 10).
germination_light(chili_pepper, darkness_required).
stratification_required(chili_pepper, false).
stratification_days_min(chili_pepper, 0).
stratification_days_max(chili_pepper, 0).
sowing_depth_cm(chili_pepper, 0.95).
minimum_soil_temp_c(chili_pepper, 18.3).
optimum_soil_temp_c(chili_pepper, 29.4).
viable_temp_min_c(chili_pepper, 15.6).
viable_temp_max_c(chili_pepper, 35.0).
special_treatment(chili_pepper, cover_seed).
special_treatment(chili_pepper, inferred_depth_from_1_4_to_1_2_inch).
source_name(chili_pepper, 'Iowa State University Extension').
source_name(chili_pepper, 'Wisconsin Horticulture Extension').
source_url(chili_pepper, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(chili_pepper, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(chili_pepper, high).

% ---------------------------------------------------------
% COCKSCOMB
% ---------------------------------------------------------
fact_scope(cockscomb, common_crop).
germination_days_min(cockscomb, 7).
germination_days_max(cockscomb, 10).
germination_light(cockscomb, darkness_required).
stratification_required(cockscomb, false).
stratification_days_min(cockscomb, 0).
stratification_days_max(cockscomb, 0).
sowing_depth_cm(cockscomb, 0.95).
special_treatment(cockscomb, cover_seed).
special_treatment(cockscomb, inferred_depth_from_1_4_to_1_2_inch).
source_name(cockscomb, 'Iowa State University Extension').
source_url(cockscomb, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(cockscomb, high).

% ---------------------------------------------------------
% COLEUS
% ---------------------------------------------------------
fact_scope(coleus, common_crop).
accepted_scientific_name(coleus, 'Coleus scutellarioides').
genus(coleus, coleus).
family(coleus, lamiaceae).
germination_days_min(coleus, 10).
germination_days_max(coleus, 14).
germination_light(coleus, light_required).
stratification_required(coleus, false).
stratification_days_min(coleus, 0).
stratification_days_max(coleus, 0).
sowing_depth_cm(coleus, 0.0).
special_treatment(coleus, do_not_cover).
special_treatment(coleus, press_seed_into_medium).
special_treatment(coleus, surface_sow).
source_name(coleus, 'Iowa State University Extension').
source_url(coleus, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(coleus, high).

% ---------------------------------------------------------
% CORN
% ---------------------------------------------------------
fact_scope(corn, common_crop).
accepted_scientific_name(corn, 'Zea mays').
genus(corn, zea).
family(corn, poaceae).
germination_days_min(corn, 4).
germination_days_max(corn, 7).
germination_light(corn, darkness_required).
stratification_required(corn, false).
stratification_days_min(corn, 0).
stratification_days_max(corn, 0).
sowing_depth_cm(corn, 0.95).
minimum_soil_temp_c(corn, 12.8).
optimum_soil_temp_c(corn, 35.0).
viable_temp_min_c(corn, 10.0).
viable_temp_max_c(corn, 40.6).
special_treatment(corn, cover_seed).
special_treatment(corn, inferred_depth_from_1_4_to_1_2_inch).
source_name(corn, 'Iowa State University Extension').
source_name(corn, 'Wisconsin Horticulture Extension').
source_url(corn, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(corn, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(corn, high).

% ---------------------------------------------------------
% COSMOS
% ---------------------------------------------------------
fact_scope(cosmos, species_plus_genus_enrichment).
accepted_scientific_name(cosmos, 'Cosmos bipinnatus').
genus(cosmos, cosmos).
family(cosmos, asteraceae).
germination_days_min(cosmos, 5).
germination_days_max(cosmos, 7).
germination_light(cosmos, darkness_required).
stratification_required(cosmos, false).
stratification_days_min(cosmos, 0).
stratification_days_max(cosmos, 0).
sowing_depth_cm(cosmos, 0.95).
special_treatment(cosmos, cover_seed).
special_treatment(cosmos, inferred_depth_from_1_4_to_1_2_inch).
special_treatment(cosmos, lightly_cover_seed).
special_treatment(cosmos, rhs_genus_match_cosmos).
source_name(cosmos, 'Iowa State University Extension').
source_name(cosmos, 'RHS Germination Guide genus Cosmos bipinnatus (cosmea)').
source_url(cosmos, 'https://www.rhs.org.uk/membership/rhs-members-seed-scheme/germination-guide').
source_url(cosmos, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(cosmos, high).

% ---------------------------------------------------------
% CREEPING ZINNIA
% ---------------------------------------------------------
fact_scope(creeping_zinnia, common_crop).
germination_days_min(creeping_zinnia, 7).
germination_days_max(creeping_zinnia, 10).
germination_light(creeping_zinnia, darkness_required).
stratification_required(creeping_zinnia, false).
stratification_days_min(creeping_zinnia, 0).
stratification_days_max(creeping_zinnia, 0).
sowing_depth_cm(creeping_zinnia, 0.95).
special_treatment(creeping_zinnia, cover_seed).
special_treatment(creeping_zinnia, inferred_depth_from_1_4_to_1_2_inch).
source_name(creeping_zinnia, 'Iowa State University Extension').
source_url(creeping_zinnia, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(creeping_zinnia, high).

% ---------------------------------------------------------
% CUCUMBER
% ---------------------------------------------------------
fact_scope(cucumber, common_crop).
accepted_scientific_name(cucumber, 'Cucumis sativus').
genus(cucumber, cucumis).
family(cucumber, cucurbitaceae).
germination_days_min(cucumber, 3).
germination_days_max(cucumber, 10).
germination_light(cucumber, darkness_required).
stratification_required(cucumber, false).
stratification_days_min(cucumber, 0).
stratification_days_max(cucumber, 0).
sowing_depth_cm(cucumber, 0.95).
minimum_soil_temp_c(cucumber, 18.3).
optimum_soil_temp_c(cucumber, 35.0).
viable_temp_min_c(cucumber, 10.0).
viable_temp_max_c(cucumber, 40.6).
special_treatment(cucumber, cover_seed).
special_treatment(cucumber, inferred_depth_from_1_4_to_1_2_inch).
source_name(cucumber, 'Iowa State University Extension').
source_name(cucumber, 'Wisconsin Horticulture Extension').
source_url(cucumber, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(cucumber, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(cucumber, high).

% ---------------------------------------------------------
% DAHLBERG DAISY
% ---------------------------------------------------------
fact_scope(dahlberg_daisy, common_crop).
germination_days_min(dahlberg_daisy, 14).
germination_days_max(dahlberg_daisy, 14).
germination_light(dahlberg_daisy, light_required).
stratification_required(dahlberg_daisy, false).
stratification_days_min(dahlberg_daisy, 0).
stratification_days_max(dahlberg_daisy, 0).
sowing_depth_cm(dahlberg_daisy, 0.0).
special_treatment(dahlberg_daisy, do_not_cover).
special_treatment(dahlberg_daisy, press_seed_into_medium).
special_treatment(dahlberg_daisy, surface_sow).
source_name(dahlberg_daisy, 'Iowa State University Extension').
source_url(dahlberg_daisy, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(dahlberg_daisy, high).

% ---------------------------------------------------------
% DILL
% ---------------------------------------------------------
fact_scope(dill, common_crop).
accepted_scientific_name(dill, 'Anethum graveolens').
genus(dill, anethum).
family(dill, apiaceae).
germination_days_min(dill, 7).
germination_days_max(dill, 14).
germination_light(dill, light_required).
stratification_required(dill, false).
stratification_days_min(dill, 0).
stratification_days_max(dill, 0).
sowing_depth_cm(dill, 0.0).
special_treatment(dill, do_not_cover).
special_treatment(dill, press_seed_into_medium).
special_treatment(dill, surface_sow).
source_name(dill, 'Iowa State University Extension').
source_url(dill, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(dill, high).

% ---------------------------------------------------------
% EGGPLANT
% ---------------------------------------------------------
fact_scope(eggplant, common_crop).
accepted_scientific_name(eggplant, 'Solanum melongena').
genus(eggplant, solanum).
family(eggplant, solanaceae).
germination_days_min(eggplant, 7).
germination_days_max(eggplant, 10).
germination_light(eggplant, darkness_required).
stratification_required(eggplant, false).
stratification_days_min(eggplant, 0).
stratification_days_max(eggplant, 0).
sowing_depth_cm(eggplant, 0.95).
special_treatment(eggplant, cover_seed).
special_treatment(eggplant, inferred_depth_from_1_4_to_1_2_inch).
source_name(eggplant, 'Iowa State University Extension').
source_url(eggplant, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(eggplant, high).

% ---------------------------------------------------------
% FLOWERING TOBACCO
% ---------------------------------------------------------
fact_scope(flowering_tobacco, species_plus_genus_enrichment).
accepted_scientific_name(flowering_tobacco, 'Nicotiana alata').
genus(flowering_tobacco, nicotiana).
family(flowering_tobacco, solanaceae).
germination_days_min(flowering_tobacco, 10).
germination_days_max(flowering_tobacco, 14).
germination_light(flowering_tobacco, light_required).
stratification_required(flowering_tobacco, false).
stratification_days_min(flowering_tobacco, 0).
stratification_days_max(flowering_tobacco, 0).
sowing_depth_cm(flowering_tobacco, 0.0).
special_treatment(flowering_tobacco, do_not_cover).
special_treatment(flowering_tobacco, press_seed_into_medium).
special_treatment(flowering_tobacco, rhs_genus_match_nicotiana).
special_treatment(flowering_tobacco, surface_sow).
source_name(flowering_tobacco, 'Iowa State University Extension').
source_name(flowering_tobacco, 'RHS Germination Guide genus Nicotiana langsdorffii (Langsdorff’s tobacco plant)').
source_url(flowering_tobacco, 'https://www.rhs.org.uk/membership/rhs-members-seed-scheme/germination-guide').
source_url(flowering_tobacco, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(flowering_tobacco, high).

% ---------------------------------------------------------
% FOUR OCLOCK
% ---------------------------------------------------------
fact_scope(four_oclock, flower).
germination_days_min(four_oclock, 5).
germination_days_max(four_oclock, 7).
germination_light(four_oclock, darkness_required).
stratification_required(four_oclock, false).
stratification_days_min(four_oclock, 0).
stratification_days_max(four_oclock, 0).
sowing_depth_cm(four_oclock, 0.95).
special_treatment(four_oclock, cover_seed).
special_treatment(four_oclock, inferred_depth_from_1_4_to_1_2_inch).
source_name(four_oclock, 'Iowa State University Extension').
source_url(four_oclock, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(four_oclock, high).

% ---------------------------------------------------------
% GERANIUM
% ---------------------------------------------------------
fact_scope(geranium, flower).
germination_days_min(geranium, 7).
germination_days_max(geranium, 21).
germination_light(geranium, darkness_required).
stratification_required(geranium, false).
stratification_days_min(geranium, 0).
stratification_days_max(geranium, 0).
sowing_depth_cm(geranium, 0.95).
special_treatment(geranium, cover_seed).
special_treatment(geranium, inferred_depth_from_1_4_to_1_2_inch).
source_name(geranium, 'Iowa State University Extension').
source_url(geranium, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(geranium, high).

% ---------------------------------------------------------
% GLOBE AMARANTH
% ---------------------------------------------------------
fact_scope(globe_amaranth, common_crop).
accepted_scientific_name(globe_amaranth, 'Gomphrena globosa').
genus(globe_amaranth, gomphrena).
family(globe_amaranth, amaranthaceae).
germination_days_min(globe_amaranth, 14).
germination_days_max(globe_amaranth, 14).
germination_light(globe_amaranth, lightly_cover).
stratification_required(globe_amaranth, false).
stratification_days_min(globe_amaranth, 0).
stratification_days_max(globe_amaranth, 0).
sowing_depth_cm(globe_amaranth, 0.3).
special_treatment(globe_amaranth, keep_close_to_surface).
special_treatment(globe_amaranth, lightly_cover_seed).
source_name(globe_amaranth, 'Iowa State University Extension').
source_url(globe_amaranth, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(globe_amaranth, high).

% ---------------------------------------------------------
% GOTU KOLA
% ---------------------------------------------------------
fact_scope(gotu_kola, extracted_profile).
accepted_scientific_name(gotu_kola, 'Centella asiatica').
genus(gotu_kola, centella).
family(gotu_kola, apiaceae).
life_cycle(gotu_kola, perennial).
botanical_life_cycle(gotu_kola, perennial).
propagation_method(gotu_kola, division).
propagation_method(gotu_kola, seed).
sunlight(gotu_kola, partial_shade).
soil_type(gotu_kola, heavy_clay).
soil_type(gotu_kola, light_sandy).
soil_type(gotu_kola, medium_loamy).
source_name(gotu_kola, 'Plants For A Future').
source_url(gotu_kola, 'https://pfaf.org/user/Plant.aspx?LatinName=Centella+asiatica').
confidence(gotu_kola, high).

% ---------------------------------------------------------
% IMPATIENS
% ---------------------------------------------------------
fact_scope(impatiens, common_crop).
accepted_scientific_name(impatiens, 'Impatiens walleriana').
genus(impatiens, impatiens).
family(impatiens, balsaminaceae).
germination_days_min(impatiens, 10).
germination_days_max(impatiens, 14).
germination_light(impatiens, light_required).
stratification_required(impatiens, false).
stratification_days_min(impatiens, 0).
stratification_days_max(impatiens, 0).
sowing_depth_cm(impatiens, 0.0).
special_treatment(impatiens, do_not_cover).
special_treatment(impatiens, press_seed_into_medium).
special_treatment(impatiens, surface_sow).
source_name(impatiens, 'Iowa State University Extension').
source_url(impatiens, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(impatiens, high).

% ---------------------------------------------------------
% KALE
% ---------------------------------------------------------
fact_scope(kale, common_crop).
accepted_scientific_name(kale, 'Brassica oleracea var. sabellica').
genus(kale, brassica).
family(kale, brassicaceae).
germination_days_min(kale, 4).
germination_days_max(kale, 7).
germination_light(kale, darkness_required).
stratification_required(kale, false).
stratification_days_min(kale, 0).
stratification_days_max(kale, 0).
sowing_depth_cm(kale, 0.95).
special_treatment(kale, cover_seed).
special_treatment(kale, inferred_depth_from_1_4_to_1_2_inch).
source_name(kale, 'Iowa State University Extension').
source_url(kale, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(kale, high).

% ---------------------------------------------------------
% KOHLRABI
% ---------------------------------------------------------
fact_scope(kohlrabi, common_crop).
germination_days_min(kohlrabi, 4).
germination_days_max(kohlrabi, 7).
germination_light(kohlrabi, darkness_required).
stratification_required(kohlrabi, false).
stratification_days_min(kohlrabi, 0).
stratification_days_max(kohlrabi, 0).
sowing_depth_cm(kohlrabi, 0.95).
special_treatment(kohlrabi, cover_seed).
special_treatment(kohlrabi, inferred_depth_from_1_4_to_1_2_inch).
source_name(kohlrabi, 'Iowa State University Extension').
source_url(kohlrabi, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(kohlrabi, high).

% ---------------------------------------------------------
% LETTUCE
% ---------------------------------------------------------
fact_scope(lettuce, common_crop).
accepted_scientific_name(lettuce, 'Lactuca sativa').
genus(lettuce, lactuca).
family(lettuce, asteraceae).
germination_days_min(lettuce, 7).
germination_days_max(lettuce, 14).
germination_light(lettuce, light_required).
stratification_required(lettuce, false).
stratification_days_min(lettuce, 0).
stratification_days_max(lettuce, 0).
sowing_depth_cm(lettuce, 0.0).
minimum_soil_temp_c(lettuce, 7.2).
optimum_soil_temp_c(lettuce, 23.9).
viable_temp_min_c(lettuce, 1.7).
viable_temp_max_c(lettuce, 29.4).
special_treatment(lettuce, do_not_cover).
special_treatment(lettuce, press_seed_into_medium).
special_treatment(lettuce, surface_sow).
source_name(lettuce, 'Iowa State University Extension').
source_name(lettuce, 'Wisconsin Horticulture Extension').
source_url(lettuce, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(lettuce, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(lettuce, high).

% ---------------------------------------------------------
% LISIANTHUS
% ---------------------------------------------------------
fact_scope(lisianthus, common_crop).
germination_days_min(lisianthus, 10).
germination_days_max(lisianthus, 14).
germination_light(lisianthus, light_required).
stratification_required(lisianthus, false).
stratification_days_min(lisianthus, 0).
stratification_days_max(lisianthus, 0).
sowing_depth_cm(lisianthus, 0.0).
special_treatment(lisianthus, do_not_cover).
special_treatment(lisianthus, press_seed_into_medium).
special_treatment(lisianthus, surface_sow).
source_name(lisianthus, 'Iowa State University Extension').
source_url(lisianthus, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(lisianthus, high).

% ---------------------------------------------------------
% MEALYCUP SAGE
% ---------------------------------------------------------
fact_scope(mealycup_sage, common_crop).
germination_days_min(mealycup_sage, 10).
germination_days_max(mealycup_sage, 14).
germination_light(mealycup_sage, light_required).
stratification_required(mealycup_sage, false).
stratification_days_min(mealycup_sage, 0).
stratification_days_max(mealycup_sage, 0).
sowing_depth_cm(mealycup_sage, 0.0).
special_treatment(mealycup_sage, do_not_cover).
special_treatment(mealycup_sage, press_seed_into_medium).
special_treatment(mealycup_sage, surface_sow).
source_name(mealycup_sage, 'Iowa State University Extension').
source_url(mealycup_sage, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(mealycup_sage, high).

% ---------------------------------------------------------
% MELAMPODIUM
% ---------------------------------------------------------
fact_scope(melampodium, common_crop).
germination_days_min(melampodium, 7).
germination_days_max(melampodium, 10).
germination_light(melampodium, lightly_cover).
stratification_required(melampodium, false).
stratification_days_min(melampodium, 0).
stratification_days_max(melampodium, 0).
sowing_depth_cm(melampodium, 0.3).
special_treatment(melampodium, keep_close_to_surface).
special_treatment(melampodium, lightly_cover_seed).
source_name(melampodium, 'Iowa State University Extension').
source_url(melampodium, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(melampodium, high).

% ---------------------------------------------------------
% MOSS ROSE
% ---------------------------------------------------------
fact_scope(moss_rose, common_crop).
accepted_scientific_name(moss_rose, 'Portulaca grandiflora').
genus(moss_rose, portulaca).
family(moss_rose, portulacaceae).
germination_days_min(moss_rose, 7).
germination_days_max(moss_rose, 10).
germination_light(moss_rose, light_required).
stratification_required(moss_rose, false).
stratification_days_min(moss_rose, 0).
stratification_days_max(moss_rose, 0).
sowing_depth_cm(moss_rose, 0.0).
special_treatment(moss_rose, do_not_cover).
special_treatment(moss_rose, press_seed_into_medium).
special_treatment(moss_rose, surface_sow).
source_name(moss_rose, 'Iowa State University Extension').
source_url(moss_rose, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(moss_rose, high).

% ---------------------------------------------------------
% MUSKMELON
% ---------------------------------------------------------
fact_scope(muskmelon, common_crop).
germination_days_min(muskmelon, 3).
germination_days_max(muskmelon, 10).
germination_light(muskmelon, darkness_required).
stratification_required(muskmelon, false).
stratification_days_min(muskmelon, 0).
stratification_days_max(muskmelon, 0).
sowing_depth_cm(muskmelon, 0.95).
special_treatment(muskmelon, cover_seed).
special_treatment(muskmelon, inferred_depth_from_1_4_to_1_2_inch).
source_name(muskmelon, 'Iowa State University Extension').
source_url(muskmelon, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(muskmelon, high).

% ---------------------------------------------------------
% ONION
% ---------------------------------------------------------
fact_scope(onion, species_plus_genus_enrichment).
accepted_scientific_name(onion, 'Allium cepa').
genus(onion, allium).
family(onion, amaryllidaceae).
germination_days_min(onion, 30).
germination_days_max(onion, 365).
germination_light(onion, light_required).
stratification_required(onion, false).
stratification_days_min(onion, 0).
stratification_days_max(onion, 0).
minimum_soil_temp_c(onion, 15.6).
optimum_soil_temp_c(onion, 23.9).
viable_temp_min_c(onion, 1.7).
viable_temp_max_c(onion, 35.0).
special_treatment(onion, leave_seed_uncovered).
special_treatment(onion, rhs_genus_match_allium).
special_treatment(onion, very_slow_germination_up_to_one_year).
source_name(onion, 'RHS Germination Guide genus Allium').
source_name(onion, 'Wisconsin Horticulture Extension').
source_url(onion, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(onion, 'https://www.rhs.org.uk/membership/pdfs/seed-scheme/harvested-seed-germination-requirements.pdf').
confidence(onion, medium).

% ---------------------------------------------------------
% PARSLEY
% ---------------------------------------------------------
fact_scope(parsley, common_crop).
accepted_scientific_name(parsley, 'Petroselinum crispum').
genus(parsley, petroselinum).
family(parsley, apiaceae).
germination_days_min(parsley, 20).
germination_days_max(parsley, 25).
germination_light(parsley, darkness_required).
stratification_required(parsley, false).
stratification_days_min(parsley, 0).
stratification_days_max(parsley, 0).
sowing_depth_cm(parsley, 0.95).
minimum_soil_temp_c(parsley, 7.2).
optimum_soil_temp_c(parsley, 23.9).
viable_temp_min_c(parsley, 4.4).
viable_temp_max_c(parsley, 32.2).
special_treatment(parsley, cover_seed).
special_treatment(parsley, inferred_depth_from_1_4_to_1_2_inch).
source_name(parsley, 'Iowa State University Extension').
source_name(parsley, 'Wisconsin Horticulture Extension').
source_url(parsley, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(parsley, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(parsley, high).

% ---------------------------------------------------------
% PEA
% ---------------------------------------------------------
fact_scope(pea, common_crop).
accepted_scientific_name(pea, 'Pisum sativum').
genus(pea, pisum).
family(pea, fabaceae).
germination_days_min(pea, 9).
germination_days_max(pea, 14).
germination_light(pea, darkness_required).
stratification_required(pea, false).
stratification_days_min(pea, 0).
stratification_days_max(pea, 0).
sowing_depth_cm(pea, 0.95).
minimum_soil_temp_c(pea, 10.0).
optimum_soil_temp_c(pea, 23.9).
viable_temp_min_c(pea, 4.4).
viable_temp_max_c(pea, 29.4).
special_treatment(pea, cover_seed).
special_treatment(pea, inferred_depth_from_1_4_to_1_2_inch).
source_name(pea, 'Iowa State University Extension').
source_name(pea, 'Wisconsin Horticulture Extension').
source_url(pea, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(pea, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(pea, high).

% ---------------------------------------------------------
% PEA ENGLISH
% ---------------------------------------------------------
fact_scope(pea_english, common_crop).
accepted_scientific_name(pea_english, 'Pisum sativum').
genus(pea_english, pisum).
family(pea_english, fabaceae).
germination_days_min(pea_english, 9).
germination_days_max(pea_english, 14).
germination_light(pea_english, darkness_required).
stratification_required(pea_english, false).
stratification_days_min(pea_english, 0).
stratification_days_max(pea_english, 0).
sowing_depth_cm(pea_english, 0.95).
minimum_soil_temp_c(pea_english, 10.0).
optimum_soil_temp_c(pea_english, 23.9).
viable_temp_min_c(pea_english, 4.4).
viable_temp_max_c(pea_english, 29.4).
special_treatment(pea_english, cover_seed).
special_treatment(pea_english, inferred_depth_from_1_4_to_1_2_inch).
source_name(pea_english, 'Iowa State University Extension').
source_name(pea_english, 'Wisconsin Horticulture Extension').
source_url(pea_english, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(pea_english, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(pea_english, high).

% ---------------------------------------------------------
% PEAS
% ---------------------------------------------------------
fact_scope(peas, common_crop).
germination_days_min(peas, 9).
germination_days_max(peas, 14).
germination_light(peas, darkness_required).
stratification_required(peas, false).
stratification_days_min(peas, 0).
stratification_days_max(peas, 0).
sowing_depth_cm(peas, 0.95).
minimum_soil_temp_c(peas, 10.0).
optimum_soil_temp_c(peas, 23.9).
viable_temp_min_c(peas, 4.4).
viable_temp_max_c(peas, 29.4).
special_treatment(peas, cover_seed).
special_treatment(peas, inferred_depth_from_1_4_to_1_2_inch).
source_name(peas, 'Iowa State University Extension').
source_name(peas, 'Wisconsin Horticulture Extension').
source_url(peas, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(peas, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(peas, high).

% ---------------------------------------------------------
% PEPPER
% ---------------------------------------------------------
fact_scope(pepper, common_crop).
accepted_scientific_name(pepper, 'Capsicum spp.').
genus(pepper, capsicum).
family(pepper, solanaceae).
germination_days_min(pepper, 7).
germination_days_max(pepper, 10).
germination_light(pepper, darkness_required).
stratification_required(pepper, false).
stratification_days_min(pepper, 0).
stratification_days_max(pepper, 0).
sowing_depth_cm(pepper, 0.95).
minimum_soil_temp_c(pepper, 18.3).
optimum_soil_temp_c(pepper, 29.4).
viable_temp_min_c(pepper, 15.6).
viable_temp_max_c(pepper, 35.0).
special_treatment(pepper, cover_seed).
special_treatment(pepper, inferred_depth_from_1_4_to_1_2_inch).
source_name(pepper, 'Iowa State University Extension').
source_name(pepper, 'Wisconsin Horticulture Extension').
source_url(pepper, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(pepper, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(pepper, high).

% ---------------------------------------------------------
% PETUNIA
% ---------------------------------------------------------
fact_scope(petunia, common_crop).
accepted_scientific_name(petunia, 'Petunia x atkinsiana').
genus(petunia, petunia).
family(petunia, solanaceae).
germination_days_min(petunia, 7).
germination_days_max(petunia, 10).
germination_light(petunia, light_required).
stratification_required(petunia, false).
stratification_days_min(petunia, 0).
stratification_days_max(petunia, 0).
sowing_depth_cm(petunia, 0.0).
special_treatment(petunia, do_not_cover).
special_treatment(petunia, press_seed_into_medium).
special_treatment(petunia, surface_sow).
source_name(petunia, 'Iowa State University Extension').
source_url(petunia, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(petunia, high).

% ---------------------------------------------------------
% PUMPKIN
% ---------------------------------------------------------
fact_scope(pumpkin, common_crop).
accepted_scientific_name(pumpkin, 'Cucurbita pepo').
genus(pumpkin, cucurbita).
family(pumpkin, cucurbitaceae).
germination_days_min(pumpkin, 5).
germination_days_max(pumpkin, 10).
germination_light(pumpkin, darkness_required).
stratification_required(pumpkin, false).
stratification_days_min(pumpkin, 0).
stratification_days_max(pumpkin, 0).
sowing_depth_cm(pumpkin, 0.95).
special_treatment(pumpkin, cover_seed).
special_treatment(pumpkin, inferred_depth_from_1_4_to_1_2_inch).
source_name(pumpkin, 'Iowa State University Extension').
source_url(pumpkin, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(pumpkin, high).

% ---------------------------------------------------------
% RADISH
% ---------------------------------------------------------
fact_scope(radish, common_crop).
accepted_scientific_name(radish, 'Raphanus sativus').
genus(radish, raphanus).
family(radish, brassicaceae).
germination_days_min(radish, 3).
germination_days_max(radish, 4).
germination_light(radish, darkness_required).
stratification_required(radish, false).
stratification_days_min(radish, 0).
stratification_days_max(radish, 0).
sowing_depth_cm(radish, 0.95).
minimum_soil_temp_c(radish, 7.2).
optimum_soil_temp_c(radish, 29.4).
viable_temp_min_c(radish, 4.4).
viable_temp_max_c(radish, 35.0).
special_treatment(radish, cover_seed).
special_treatment(radish, inferred_depth_from_1_4_to_1_2_inch).
source_name(radish, 'Iowa State University Extension').
source_name(radish, 'Wisconsin Horticulture Extension').
source_url(radish, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(radish, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(radish, high).

% ---------------------------------------------------------
% RED SALVIA
% ---------------------------------------------------------
fact_scope(red_salvia, common_crop).
germination_days_min(red_salvia, 10).
germination_days_max(red_salvia, 14).
germination_light(red_salvia, light_required).
stratification_required(red_salvia, false).
stratification_days_min(red_salvia, 0).
stratification_days_max(red_salvia, 0).
sowing_depth_cm(red_salvia, 0.0).
special_treatment(red_salvia, do_not_cover).
special_treatment(red_salvia, press_seed_into_medium).
special_treatment(red_salvia, surface_sow).
source_name(red_salvia, 'Iowa State University Extension').
source_url(red_salvia, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(red_salvia, high).

% ---------------------------------------------------------
% SNAPDRAGON
% ---------------------------------------------------------
fact_scope(snapdragon, species_plus_genus_enrichment).
accepted_scientific_name(snapdragon, 'Antirrhinum majus').
genus(snapdragon, antirrhinum).
family(snapdragon, plantaginaceae).
germination_days_min(snapdragon, 7).
germination_days_max(snapdragon, 14).
germination_light(snapdragon, light_required).
stratification_required(snapdragon, false).
stratification_days_min(snapdragon, 0).
stratification_days_max(snapdragon, 0).
sowing_depth_cm(snapdragon, 0.0).
special_treatment(snapdragon, do_not_cover).
special_treatment(snapdragon, leave_seed_uncovered).
special_treatment(snapdragon, press_seed_into_medium).
special_treatment(snapdragon, requires_light_to_germinate).
special_treatment(snapdragon, rhs_genus_match_antirrhinum).
special_treatment(snapdragon, surface_sow).
source_name(snapdragon, 'Iowa State University Extension').
source_name(snapdragon, 'RHS Germination Guide genus Antirrhinum').
source_url(snapdragon, 'https://www.rhs.org.uk/membership/pdfs/seed-scheme/harvested-seed-germination-requirements.pdf').
source_url(snapdragon, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(snapdragon, high).

% ---------------------------------------------------------
% SPINACH
% ---------------------------------------------------------
fact_scope(spinach, common_crop).
accepted_scientific_name(spinach, 'Spinacia oleracea').
genus(spinach, spinacia).
family(spinach, amaranthaceae).
stratification_required(spinach, false).
stratification_days_min(spinach, 0).
stratification_days_max(spinach, 0).
minimum_soil_temp_c(spinach, 7.2).
optimum_soil_temp_c(spinach, 21.1).
viable_temp_min_c(spinach, 1.7).
viable_temp_max_c(spinach, 29.4).
source_name(spinach, 'Wisconsin Horticulture Extension').
source_url(spinach, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(spinach, medium).

% ---------------------------------------------------------
% SQUASH
% ---------------------------------------------------------
fact_scope(squash, common_crop).
accepted_scientific_name(squash, 'Cucurbita pepo').
genus(squash, cucurbita).
family(squash, cucurbitaceae).
germination_days_min(squash, 5).
germination_days_max(squash, 10).
germination_light(squash, darkness_required).
stratification_required(squash, false).
stratification_days_min(squash, 0).
stratification_days_max(squash, 0).
sowing_depth_cm(squash, 0.95).
minimum_soil_temp_c(squash, 21.1).
optimum_soil_temp_c(squash, 35.0).
viable_temp_min_c(squash, 15.6).
viable_temp_max_c(squash, 37.8).
special_treatment(squash, cover_seed).
special_treatment(squash, inferred_depth_from_1_4_to_1_2_inch).
source_name(squash, 'Iowa State University Extension').
source_name(squash, 'Wisconsin Horticulture Extension').
source_url(squash, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(squash, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(squash, high).

% ---------------------------------------------------------
% STRAWFLOWER
% ---------------------------------------------------------
fact_scope(strawflower, common_crop).
germination_days_min(strawflower, 7).
germination_days_max(strawflower, 10).
germination_light(strawflower, lightly_cover).
stratification_required(strawflower, false).
stratification_days_min(strawflower, 0).
stratification_days_max(strawflower, 0).
sowing_depth_cm(strawflower, 0.3).
special_treatment(strawflower, keep_close_to_surface).
special_treatment(strawflower, lightly_cover_seed).
source_name(strawflower, 'Iowa State University Extension').
source_url(strawflower, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(strawflower, high).

% ---------------------------------------------------------
% SWEET CORN
% ---------------------------------------------------------
fact_scope(sweet_corn, common_crop).
germination_days_min(sweet_corn, 4).
germination_days_max(sweet_corn, 7).
germination_light(sweet_corn, darkness_required).
stratification_required(sweet_corn, false).
stratification_days_min(sweet_corn, 0).
stratification_days_max(sweet_corn, 0).
sowing_depth_cm(sweet_corn, 0.95).
minimum_soil_temp_c(sweet_corn, 12.8).
optimum_soil_temp_c(sweet_corn, 35.0).
viable_temp_min_c(sweet_corn, 10.0).
viable_temp_max_c(sweet_corn, 40.6).
special_treatment(sweet_corn, cover_seed).
special_treatment(sweet_corn, inferred_depth_from_1_4_to_1_2_inch).
source_name(sweet_corn, 'Iowa State University Extension').
source_name(sweet_corn, 'Wisconsin Horticulture Extension').
source_url(sweet_corn, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(sweet_corn, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(sweet_corn, high).

% ---------------------------------------------------------
% SWISS CHARD
% ---------------------------------------------------------
fact_scope(swiss_chard, common_crop).
accepted_scientific_name(swiss_chard, 'Beta vulgaris subsp. vulgaris').
genus(swiss_chard, beta).
family(swiss_chard, amaranthaceae).
stratification_required(swiss_chard, false).
stratification_days_min(swiss_chard, 0).
stratification_days_max(swiss_chard, 0).
minimum_soil_temp_c(swiss_chard, 12.8).
optimum_soil_temp_c(swiss_chard, 29.4).
viable_temp_min_c(swiss_chard, 4.4).
viable_temp_max_c(swiss_chard, 35.0).
source_name(swiss_chard, 'Wisconsin Horticulture Extension').
source_url(swiss_chard, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(swiss_chard, medium).

% ---------------------------------------------------------
% TOMATO
% ---------------------------------------------------------
fact_scope(tomato, common_crop).
accepted_scientific_name(tomato, 'Solanum lycopersicum').
genus(tomato, solanum).
family(tomato, solanaceae).
germination_days_min(tomato, 6).
germination_days_max(tomato, 12).
germination_light(tomato, darkness_required).
stratification_required(tomato, false).
stratification_days_min(tomato, 0).
stratification_days_max(tomato, 0).
sowing_depth_cm(tomato, 0.95).
minimum_soil_temp_c(tomato, 21.1).
optimum_soil_temp_c(tomato, 29.4).
viable_temp_min_c(tomato, 10.0).
viable_temp_max_c(tomato, 35.0).
special_treatment(tomato, cover_seed).
special_treatment(tomato, inferred_depth_from_1_4_to_1_2_inch).
source_name(tomato, 'Iowa State University Extension').
source_name(tomato, 'Wisconsin Horticulture Extension').
source_url(tomato, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
source_url(tomato, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(tomato, high).

% ---------------------------------------------------------
% TURNIP
% ---------------------------------------------------------
fact_scope(turnip, common_crop).
accepted_scientific_name(turnip, 'Brassica rapa subsp. rapa').
genus(turnip, brassica).
family(turnip, brassicaceae).
stratification_required(turnip, false).
stratification_days_min(turnip, 0).
stratification_days_max(turnip, 0).
minimum_soil_temp_c(turnip, 10.0).
optimum_soil_temp_c(turnip, 29.4).
viable_temp_min_c(turnip, 4.4).
viable_temp_max_c(turnip, 40.6).
source_name(turnip, 'Wisconsin Horticulture Extension').
source_url(turnip, 'https://hort.extension.wisc.edu/articles/when-is-the-right-time-to-plant-vegetable-seeds-check-soil-temperature/').
confidence(turnip, medium).

% ---------------------------------------------------------
% VINCA
% ---------------------------------------------------------
fact_scope(vinca, common_crop).
germination_days_min(vinca, 14).
germination_days_max(vinca, 14).
germination_light(vinca, lightly_cover).
stratification_required(vinca, false).
stratification_days_min(vinca, 0).
stratification_days_max(vinca, 0).
sowing_depth_cm(vinca, 0.3).
special_treatment(vinca, keep_close_to_surface).
special_treatment(vinca, lightly_cover_seed).
source_name(vinca, 'Iowa State University Extension').
source_url(vinca, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(vinca, high).

% ---------------------------------------------------------
% WATERMELON
% ---------------------------------------------------------
fact_scope(watermelon, common_crop).
accepted_scientific_name(watermelon, 'Citrullus lanatus').
genus(watermelon, citrullus).
family(watermelon, cucurbitaceae).
germination_days_min(watermelon, 3).
germination_days_max(watermelon, 10).
germination_light(watermelon, darkness_required).
stratification_required(watermelon, false).
stratification_days_min(watermelon, 0).
stratification_days_max(watermelon, 0).
sowing_depth_cm(watermelon, 0.95).
special_treatment(watermelon, cover_seed).
special_treatment(watermelon, inferred_depth_from_1_4_to_1_2_inch).
source_name(watermelon, 'Iowa State University Extension').
source_url(watermelon, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(watermelon, high).

% ---------------------------------------------------------
% WAX BEGONIA
% ---------------------------------------------------------
fact_scope(wax_begonia, common_crop).
germination_days_min(wax_begonia, 14).
germination_days_max(wax_begonia, 14).
germination_light(wax_begonia, light_required).
stratification_required(wax_begonia, false).
stratification_days_min(wax_begonia, 0).
stratification_days_max(wax_begonia, 0).
sowing_depth_cm(wax_begonia, 0.0).
special_treatment(wax_begonia, do_not_cover).
special_treatment(wax_begonia, press_seed_into_medium).
special_treatment(wax_begonia, surface_sow).
source_name(wax_begonia, 'Iowa State University Extension').
source_url(wax_begonia, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(wax_begonia, high).

% ---------------------------------------------------------
% ZINNIA
% ---------------------------------------------------------
fact_scope(zinnia, common_crop).
germination_days_min(zinnia, 5).
germination_days_max(zinnia, 7).
germination_light(zinnia, darkness_required).
stratification_required(zinnia, false).
stratification_days_min(zinnia, 0).
stratification_days_max(zinnia, 0).
sowing_depth_cm(zinnia, 0.95).
special_treatment(zinnia, cover_seed).
special_treatment(zinnia, inferred_depth_from_1_4_to_1_2_inch).
source_name(zinnia, 'Iowa State University Extension').
source_url(zinnia, 'https://yardandgarden.extension.iastate.edu/how-to/germination-requirements-annuals-and-vegetables').
confidence(zinnia, high).


% =========================================================
% UNGROUPED / NON-PLANT FACTS
% =========================================================

:- discontiguous accepted_scientific_name/2.
:- discontiguous confidence/2.
:- discontiguous fact_scope/2.
:- discontiguous family/2.
:- discontiguous genus/2.
:- discontiguous germination_days_max/2.
:- discontiguous germination_days_min/2.
:- discontiguous germination_light/2.
:- discontiguous minimum_soil_temp_c/2.
:- discontiguous optimum_soil_temp_c/2.
:- discontiguous source_name/2.
:- discontiguous source_url/2.
:- discontiguous sowing_depth_cm/2.
:- discontiguous special_treatment/2.
:- discontiguous stratification_days_max/2.
:- discontiguous stratification_days_min/2.
:- discontiguous stratification_required/2.
:- discontiguous viable_temp_max_c/2.
:- discontiguous viable_temp_min_c/2.
:- multifile accepted_scientific_name/2.
:- multifile family/2.
:- multifile genus/2.
