#!/usr/bin/env python3
"""
export_pests_to_prolog.py

Exports normalized PNW pest profiles into Prolog.

Input:
- data_bank/normalized/pests_merged/*.json

Output:
- data_bank/exports/prolog/generated_pnw_pest_interactions.pl

Generated predicates:
- pest/1
- pest_type/2
- pest_scientific_name/2
- pest_included_species/3
- damage_symptom/2
- attacks/2, only when host_plants exists
- pest_source/2
- pest_source_url/2
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Set

SCRIPT_DIR = Path(__file__).resolve().parents[1]
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from project_paths import PATHS  # noqa: E402

SOURCE_ATOM = "pnw_insect_management_handbook"


def normalize_text(value: str) -> str:
    value = str(value).replace("\xa0", " ")
    value = re.sub(r"\s+", " ", value)
    return value.strip()


def to_atom(value: str) -> str:
    value = normalize_text(value).lower()
    value = value.replace("&", " and ")
    value = re.sub(r"\([^)]*\)", "", value)
    value = re.sub(r"[^a-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value)
    return value.strip("_")


def quote_prolog_string(value: str) -> str:
    value = str(value).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{value}'"


def load_profiles(input_dir: Path) -> List[Dict[str, Any]]:
    profiles = []

    for path in sorted(input_dir.glob("*.json")):
        try:
            profiles.append(json.loads(path.read_text(encoding="utf-8")))
        except Exception as exc:
            print(f"[WARN] Could not read {path}: {exc}")

    return profiles


def emit(lines: List[str], seen: Set[str], line: str) -> None:
    if line not in seen:
        lines.append(line)
        seen.add(line)


def build_prolog(profiles: List[Dict[str, Any]]) -> str:
    lines: List[str] = []
    seen: Set[str] = set()

    lines.append("% =========================================================")
    lines.append("% Generated PNW pest facts")
    lines.append("% Source: PNW Common Pests of Vegetable Crops")
    lines.append("% Generated by: scripts/export_pests_to_prolog.py")
    lines.append(f"% Generated at: {datetime.now(timezone.utc).isoformat()}")
    lines.append("% =========================================================")
    lines.append("")

    for profile in sorted(profiles, key=lambda item: item.get("pest_atom", "")):
        pest = to_atom(profile.get("pest_atom") or "")
        if not pest:
            continue

        lines.append("")
        lines.append(f"% --- {pest} ---")

        emit(lines, seen, f"pest({pest}).")

        pest_type = to_atom(profile.get("pest_type") or "insect")
        emit(lines, seen, f"pest_type({pest}, {pest_type}).")
        emit(lines, seen, f"pest_source({pest}, {SOURCE_ATOM}).")

        for sci in profile.get("scientific_names", []) or []:
            sci_atom = to_atom(sci)
            if sci_atom:
                emit(lines, seen, f"pest_scientific_name({pest}, {sci_atom}).")

        for item in profile.get("included_species", []) or []:
            common_name = item.get("common_name")
            scientific_name = item.get("scientific_name")

            common_atom = to_atom(common_name) if common_name else "unknown"
            scientific_atom = to_atom(scientific_name) if scientific_name else "unknown"

            if common_atom != "unknown" or scientific_atom != "unknown":
                emit(
                    lines,
                    seen,
                    f"pest_included_species({pest}, {common_atom}, {scientific_atom}).",
                )

        for host in profile.get("host_plants", []) or []:
            host_atom = to_atom(host)
            if host_atom:
                emit(lines, seen, f"attacks({pest}, {host_atom}).")

        for tag in profile.get("damage_tags", []) or []:
            tag_atom = to_atom(tag)
            if tag_atom:
                emit(lines, seen, f"damage_symptom({pest}, {tag_atom}).")

        source_url = profile.get("source_url")
        if source_url:
            emit(
                lines,
                seen,
                f"pest_source_url({pest}, {quote_prolog_string(source_url)}).",
            )

    lines.append("")
    return "\n".join(lines)


def print_summary(profiles: List[Dict[str, Any]]) -> None:
    pests = {p.get("pest_atom") for p in profiles if p.get("pest_atom")}
    scientific = {sci for p in profiles for sci in p.get("scientific_names", []) or []}
    damage_tags = {tag for p in profiles for tag in p.get("damage_tags", []) or []}
    attacks = sum(len(p.get("host_plants", []) or []) for p in profiles)

    print("")
    print("========== PNW PROLOG EXPORT SUMMARY ==========")
    print(f"Pests:            {len(pests)}")
    print(f"Scientific names: {len(scientific)}")
    print(f"Damage tags:      {len(damage_tags)}")
    print(f"Attack facts:     {attacks}")
    print("===============================================")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input-dir",
        default=str(PATHS.data_bank_normalized / "pests_merged"),
    )
    parser.add_argument(
        "--output",
        default=str(PATHS.data_bank / "exports" / "prolog" / "generated_pnw_pest_interactions.pl"),
    )

    args = parser.parse_args()

    profiles = load_profiles(Path(args.input_dir))
    prolog_text = build_prolog(profiles)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(prolog_text, encoding="utf-8")

    print(f"[OK] Wrote: {output_path}")
    print_summary(profiles)


if __name__ == "__main__":
    main()
