"""add crop plan groups and polyculture fields

Revision ID: 2b35d0fed869
Revises: e5914ac287db
Create Date: 2026-05-27 11:45:23.775853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b35d0fed869"
down_revision: Union[str, Sequence[str], None] = "e5914ac287db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_plan_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("crop_plan_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("group_number", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=True),
        sa.Column("main_crops", sa.JSON(), nullable=False),
        sa.Column("suggested_companions", sa.JSON(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=True),
        sa.Column("allocated_area_m2", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["crop_plan_id"], ["crop_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["farm_sections.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crop_plan_groups_id"), "crop_plan_groups", ["id"], unique=False)
    op.add_column("crop_plans", sa.Column("location_id", sa.Integer(), nullable=True))
    op.add_column("crop_plans", sa.Column("name", sa.String(length=150), nullable=True))
    op.add_column("crop_plans", sa.Column("plan_type", sa.String(length=50), nullable=True))
    op.alter_column("crop_plans", "crop_name", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.create_foreign_key(None, "crop_plans", "locations", ["location_id"], ["id"], ondelete="SET NULL")
    op.add_column("production_batches", sa.Column("crop_plan_group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "production_batches", "crop_plan_groups", ["crop_plan_group_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "production_batches", type_="foreignkey")
    op.drop_column("production_batches", "crop_plan_group_id")
    op.drop_constraint(None, "crop_plans", type_="foreignkey")
    op.alter_column("crop_plans", "crop_name", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.drop_column("crop_plans", "plan_type")
    op.drop_column("crop_plans", "name")
    op.drop_column("crop_plans", "location_id")
    op.drop_index(op.f("ix_crop_plan_groups_id"), table_name="crop_plan_groups")
    op.drop_table("crop_plan_groups")
    # ### end Alembic commands ###
