"""add production planning and lifecycle tables

Revision ID: 337ab8cb9b02
Revises: c9d3e7f1a204
Create Date: 2026-05-26 12:56:05.822438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "337ab8cb9b02"
down_revision: Union[str, Sequence[str], None] = "c9d3e7f1a204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("crop_name", sa.String(length=100), nullable=False),
        sa.Column("target_yield", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("target_yield_unit", sa.String(length=50), nullable=True),
        sa.Column("total_area_m2", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("germination_days", sa.Integer(), nullable=True),
        sa.Column("transplant_days", sa.Integer(), nullable=True),
        sa.Column("harvest_days", sa.Integer(), nullable=True),
        sa.Column("desired_harvest_interval_days", sa.Integer(), nullable=True),
        sa.Column("planned_start_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crop_plans_id"), "crop_plans", ["id"], unique=False)
    op.create_table(
        "farm_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("width_m", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("length_m", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("area_m2", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("section_type", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_farm_sections_id"), "farm_sections", ["id"], unique=False)
    op.create_table(
        "production_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("crop_plan_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("batch_number", sa.Integer(), nullable=False),
        sa.Column("seed_start_date", sa.Date(), nullable=False),
        sa.Column("expected_germination_date", sa.Date(), nullable=False),
        sa.Column("transplant_date", sa.Date(), nullable=False),
        sa.Column("expected_harvest_start", sa.Date(), nullable=False),
        sa.Column("expected_harvest_end", sa.Date(), nullable=False),
        sa.Column("allocated_area_m2", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("expected_yield", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["crop_plan_id"], ["crop_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["farm_sections.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_production_batches_id"), "production_batches", ["id"], unique=False)
    op.create_table(
        "growth_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("recorded_date", sa.Date(), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("width_cm", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("leaf_count", sa.Integer(), nullable=True),
        sa.Column("health_status", sa.String(length=50), nullable=True),
        sa.Column("vigor_score", sa.Integer(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["production_batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_growth_snapshots_id"), "growth_snapshots", ["id"], unique=False)
    op.create_table(
        "harvest_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("harvest_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("quality_grade", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["production_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_harvest_records_id"), "harvest_records", ["id"], unique=False)
    op.create_table(
        "planning_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("crop_plan_id", sa.Integer(), nullable=True),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("trigger_date", sa.Date(), nullable=False),
        sa.Column("is_sent", sa.Boolean(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["production_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["crop_plan_id"], ["crop_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_planning_notifications_id"), "planning_notifications", ["id"], unique=False)
    op.create_table(
        "plant_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["production_batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plant_events_id"), "plant_events", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plant_events_id"), table_name="plant_events")
    op.drop_table("plant_events")
    op.drop_index(op.f("ix_planning_notifications_id"), table_name="planning_notifications")
    op.drop_table("planning_notifications")
    op.drop_index(op.f("ix_harvest_records_id"), table_name="harvest_records")
    op.drop_table("harvest_records")
    op.drop_index(op.f("ix_growth_snapshots_id"), table_name="growth_snapshots")
    op.drop_table("growth_snapshots")
    op.drop_index(op.f("ix_production_batches_id"), table_name="production_batches")
    op.drop_table("production_batches")
    op.drop_index(op.f("ix_farm_sections_id"), table_name="farm_sections")
    op.drop_table("farm_sections")
    op.drop_index(op.f("ix_crop_plans_id"), table_name="crop_plans")
    op.drop_table("crop_plans")
    # ### end Alembic commands ###
