"""test change

Revision ID: a8620439b9bf
Revises: 2b8aacb11c5a
Create Date: 2026-04-18 14:38:01.898027

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import context, op

# revision identifiers, used by Alembic.
revision: str = "a8620439b9bf"
down_revision: Union[str, Sequence[str], None] = "2b8aacb11c5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("plant_species_cache", "plant_species")
    if context.get_context().dialect.name == "postgresql":
        op.execute("ALTER INDEX IF EXISTS ix_plant_species_cache_id RENAME TO ix_plant_species_id")
        op.execute("ALTER TABLE plant_species " "RENAME CONSTRAINT plant_species_cache_external_id_key TO plant_species_external_id_key")
    op.add_column("soil_conditions", sa.Column("data_source", sa.String(length=50), nullable=True))
    op.drop_column("soil_conditions", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "soil_conditions",
        sa.Column("source", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_column("soil_conditions", "data_source")
    if context.get_context().dialect.name == "postgresql":
        op.execute("ALTER INDEX IF EXISTS ix_plant_species_id RENAME TO ix_plant_species_cache_id")
        op.execute("ALTER TABLE plant_species " "RENAME CONSTRAINT plant_species_external_id_key TO plant_species_cache_external_id_key")
    op.rename_table("plant_species", "plant_species_cache")
    # ### end Alembic commands ###
