"""sync production batch fields

Revision ID: e5914ac287db
Revises: 337ab8cb9b02
Create Date: 2026-05-26 13:01:14.673553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5914ac287db"
down_revision: Union[str, Sequence[str], None] = "337ab8cb9b02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("production_batches", sa.Column("expected_transplant_date", sa.Date(), nullable=True))
    op.add_column("production_batches", sa.Column("expected_harvest_date", sa.Date(), nullable=True))
    op.add_column("production_batches", sa.Column("actual_harvest_date", sa.Date(), nullable=True))
    op.add_column("production_batches", sa.Column("actual_yield", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column("production_batches", sa.Column("yield_unit", sa.String(length=50), nullable=True))
    op.alter_column("production_batches", "expected_germination_date", existing_type=sa.DATE(), nullable=True)
    op.drop_column("production_batches", "expected_harvest_start")
    op.drop_column("production_batches", "transplant_date")
    op.drop_column("production_batches", "expected_harvest_end")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("production_batches", sa.Column("expected_harvest_end", sa.DATE(), autoincrement=False, nullable=False))
    op.add_column("production_batches", sa.Column("transplant_date", sa.DATE(), autoincrement=False, nullable=False))
    op.add_column("production_batches", sa.Column("expected_harvest_start", sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column("production_batches", "expected_germination_date", existing_type=sa.DATE(), nullable=False)
    op.drop_column("production_batches", "yield_unit")
    op.drop_column("production_batches", "actual_yield")
    op.drop_column("production_batches", "actual_harvest_date")
    op.drop_column("production_batches", "expected_harvest_date")
    op.drop_column("production_batches", "expected_transplant_date")
    # ### end Alembic commands ###
